sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - make setup
script:
  # Check build
  - make
  # Flake8
  - make lint
  # confirm doc builds look good
  - make docs
  # Testing with coverage
  - make travis-test
